# Deployment do Postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:14.4
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "NeruTr212@Ht"
        - name: POSTGRES_USER
          value: "kubenews"
        - name: POSTGRES_DB
          value: "kubenews"  

---
# Services Postgres
apiVersion: v1
kind: Service
metadata:
   name: postgre
spec:
  selector:
     app: postgre
  ports:
  - port: 5432
    targetPort: 5432
  
---

# Aplicacao
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: mzamulticloud/kube-news:v1
        env:
        - name: DB_DATABASE
          value: "kubenews"
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD
          value: "NeruTr212@Ht"
        - name: DB_HOST
          value: "postgre"

---

# Service Aplicaco
apiVersion: v1
kind: Service
metadata:
   name: kube-news
spec:
  selector:
     app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000     
  type: LoadBalancer    
