# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Autenticando o usuario no Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Contruindo a imagem e enviando a imagem para o Docker
        uses: docker/build-push-action@v3.1.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            mzamulticloud/conversao-temperatura-ago22:latest
            mzamulticloud/conversao-temperatura-ago22:${{github.run_number}}
            
  CD:
   runs-on: ubuntu-latest
   needs: [CI]
   steps:
     - uses: actions/checkout@v3

     - name: Definindo o kube config
       uses: Azure/k8s-set-context@v3.0
       with:
         method: kubeconfig
         kubeconfig: ${{secrets.K8S_CONFIG}}

     - name: Efetuando o deploy no ambiente de teste
       uses: Azure/k8s-deploy@v4.3
       with:
         images: mzamulticloud/conversao-temperatura-ago22:${{github.run_number}}
         manifests: |
            k8s/deployment.yaml
   
     
     
  
             
          
     
   
